
[package]
name = "ubl-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
aws-config = "1"
aws-sdk-s3 = "1"
tokio = { version = "1", features = ["macros"] }
anyhow = "1"
